import type { World } from "../types";
import type { ActiveNewsEvent, NewsEventsState } from "./types";
import { decayBias, maybeQueueNewsRequest, type NewsSpawnRequest } from "./spawn";
import { invalidateEventCache } from "./modifier";

export function createNewsEventsState(): NewsEventsState {
  return { enabled: true, active: [], recent: [], bias: {}, nextEventId: 1 };
}

export interface NewsTickReport {
  spawned: ActiveNewsEvent[];           // events newly applied this tick (lands when /api/news/event responses arrive — usually empty for the spawn-cadence tick itself)
  expired: ActiveNewsEvent[];
  // When non-null, the UI should fire an /api/news/event request with this
  // spec. The UI's news client throttles concurrent in-flight requests; if
  // the counter is at the cap, the request is dropped on the floor and the
  // next cadence tick will roll fresh.
  spawnRequest: NewsSpawnRequest | null;
}

export function tickNewsEvents(world: World): NewsTickReport {
  // Always invalidate at tick boundary so the per-tick cache doesn't leak.
  invalidateEventCache(world);

  const state = world.newsEvents;
  const spawned: ActiveNewsEvent[] = [];
  const expired: ActiveNewsEvent[] = [];
  if (!state) return { spawned, expired, spawnRequest: null };

  // 1) Expire — move past-expiry events into recent (capped).
  if (state.active.length > 0) {
    const stillActive: ActiveNewsEvent[] = [];
    for (const ev of state.active) {
      if (ev.expiresAt <= world.tick) {
        expired.push(ev);
        state.recent.push({
          uid: ev.uid,
          templateId: ev.templateId,
          tick: world.tick,
          effects: ev.effects,
        });
      } else {
        stillActive.push(ev);
      }
    }
    state.active = stillActive;
    if (state.recent.length > 64) {
      state.recent.splice(0, state.recent.length - 64);
    }
  }

  // 2) Bias decay — runs every tick so long-run drift trends to zero.
  decayBias(state);

  // 3) Spawn — cadence-gated. Returns a request spec rather than a
  // resolved event since events are now generated by the LLM endpoint.
  // Concurrency is enforced client-side (sim doesn't track in-flight).
  let spawnRequest: NewsSpawnRequest | null = null;
  if (state.enabled) {
    spawnRequest = maybeQueueNewsRequest(world);
  }

  if (expired.length > 0) {
    invalidateEventCache(world);
  }

  return { spawned, expired, spawnRequest };
}
